services:
  setthedate:
    image: ${DOCKER_REGISTRY-}setthedate
    build:
      context: .
      dockerfile: SetTheDate/Dockerfile
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: setthedate
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
